#!/bin/bash

echo "========================================================"
echo "      CodeCouncil AI - Stripe Setup Helper"
echo "========================================================"
echo ""
echo "This script will help you configure the required Stripe Products."
echo "You can either run these commands with the Stripe CLI or create them manually in the Dashboard."
echo ""

echo "--------------------------------------------------------"
echo "1. Startup Audit Plan"
echo "--------------------------------------------------------"
echo "Product Name: Startup Audit"
echo "Description: Essential validation for MVPs."
echo ""
echo "  [Monthly Price]"
echo "  Amount: \$49.00 USD"
echo "  Interval: Monthly"
echo "  ID to save in .env as STRIPE_PRICE_STARTUP_MONTHLY"
echo ""
echo "  [Annual Price]"
echo "  Amount: \$499.00 USD"
echo "  Interval: Yearly"
echo "  ID to save in .env as STRIPE_PRICE_STARTUP_ANNUAL"
echo ""

echo "--------------------------------------------------------"
echo "2. Enterprise Deep Dive Plan"
echo "--------------------------------------------------------"
echo "Product Name: Enterprise Deep Dive"
echo "Description: Full compliance and security audit."
echo ""
echo "  [Monthly Price]"
echo "  Amount: \$149.00 USD"
echo "  Interval: Monthly"
echo "  ID to save in .env as STRIPE_PRICE_ENTERPRISE_MONTHLY"
echo ""
echo "  [Annual Price]"
echo "  Amount: \$1499.00 USD"
echo "  Interval: Yearly"
echo "  ID to save in .env as STRIPE_PRICE_ENTERPRISE_ANNUAL"
echo ""

echo "========================================================"
echo "NEXT STEPS:"
echo "1. Go to https://dashboard.stripe.com/products"
echo "2. Create the products as described above."
echo "3. Copy the 'Price API ID' (starts with price_...) for each."
echo "4. Paste them into backend/.env"
echo "========================================================"
